window.DDA_EVENTS = [
  {
    slug: "blind-duck-dating-registry-deadline-april-2026",
    name: "Blind Duck Dating",
    shortName: "BDD",
    date: "2026-04-04",
    dateText: "4th April 2026",
    location: "Throughout Berlin",
    frequency: "Ongoing",
    badge: "Registry deadline",
    cardBg: "#e6f7ff",
    logo: "./images/BDD logo.png",
    logoAlt: "Blind Duck Dating logo",
    shortDescription: "Curated face-to-face meeting with 8 people. Register before the current deadline.",
    ctaText: "Register to the Dating Flock",
    externalUrl: "https://forms.gle/iKNUU8ozepe3AWfb6",
    applicationUrl: "https://forms.gle/iKNUU8ozepe3AWfb6",
    deadlineText: "Registry deadline: 4th April 2026"
  },
  {
    slug: "poly-speed-dating-may-2026",
    name: "Poly Speed Dating",
    shortName: "PSD",
    date: "2026-05-17",
    dateText: "17th May 2026",
    location: "Near Treptower Park, Berlin",
    frequency: "Every few months",
    badge: "5th edition",
    cardBg: "#ffeb2b",
    logo: "./images/PSD logo.png",
    logoAlt: "Poly Speed Dating logo",
    shortDescription: "A moderated in-person event for polyamorous people to meet and connect.",
    ctaText: "Open PSD Website",
    externalUrl: "https://poly-speed-dating.onrender.com/",
    applicationUrl: "https://poly-speed-dating.onrender.com/",
    deadlineText: ""
  },
  {
    slug: "poly-fest-november-2026",
    name: "Poly Fest",
    shortName: "PF",
    date: "2026-11-23",
    dateText: "23rd November 2026",
    location: "Berlin",
    frequency: "Special event",
    badge: "23.11.2026 - International Polyamorous Day",
    cardBg: "#ffe4cc",
    logo: "/images/PolyFest_logo.png",
    logoAlt: "Poly Fest logo",
    shortDescription: "Poly Fest gathering in Berlin.",
    ctaText: "Open event page",
    externalUrl: "https://poly-speed-dating.onrender.com/polyfest.html",
    applicationUrl: "https://poly-speed-dating.onrender.com/polyfest.html",
    deadlineText: ""
  }
];